id: xuhuaiyu
kind: person
owner: xuhuaiyu
description: >
  TiDB-oriented PR review heuristics focusing on correctness, concurrency, security,
  compatibility, and reproducible verification.
preferred_tags:
  - lang:go
  - lang:sql
  - risk:correctness
  - risk:concurrency
  - risk:security
  - risk:compat
  - theme:testing
  - theme:error-handling
excluded_tags: []
review_components:
  - component:execution
  - component:planner
  - component:sql-infra
  - component:ddl
  - component:statistics
  - component:dumpling
participation:
  max_rules: 8
id: xuhuaiyu
kind: person
owner: xuhuaiyu
description: TiDB PR review heuristics with Go correctness, concurrency, and testing focus
preferred_tags:
  - scope:tidb
  - lang:go
  - risk:correctness
  - risk:concurrency
  - theme:error-handling
excluded_tags: []
review_scope:
  - scope:tidb
participation:
  max_rules: 12
