id: pr-baseline
kind: process
owner: core
description: Baseline PR review workflow
priority: 10
cost: light
mode: exclusive
default: true
output_contract:
  - review.md
  - review.json
preferred_tags: []
activation:
  required_tags: []
  any_tags: []
  min_files: 0
  scopes: []
  langs: []
